---
title: "Building process of this blog"
author: "Yijia Zhao"
date: "2026-02-16"
categories: [Misc]
format: html
---

## Technical Details

This blog is built by [Quarto](https://quarto.org), which is a powerful open-source scientific and technical publishing system built on Pandoc (written by AI in vscode). \ 
I choose **Quarto** for its support for $Tex$ formulas. My first choice was [Hexo](https://hexo.io). However, after spending an entire afternoon trying to configure it to support $Tex$ formulas--experimenting with renderers for $MathJax$, which failed to render formulas entirely, and $KaTex$, which produced ghosting arrtifacts and displayed raw $Tex$ code on the page--I ultimately decided to switch to **Quarto** on *7th Feb, 2026*.\
\
The source code of this blog is available on [GitHub](https://github.com/Yijia-phys/my-blog). It was not my firstr time using **git**--I had previouly used it to upload my Obsidian vault to Github. But back then, I simply followed a tutorial posts machanically to set it up, and through an Obsidian plugin, I could have it automatically sync when closing Obsidian or after a certain time interval. I did not actually understand what those commands meant.\
\
During the process of building this blog, I began to truly understand the meaning of Git commands, such as `git commit` and `git push`. More interestingly, following some advice, I wrote a simple `.ps1` script:

```powershell
quarto render
git add .
git commit -m "Update blog: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
git push origin main
```

While I have observed that many seasoned GitHub users opt for brief descriptive commit messages rather than including dates, I do not yet find this practice necessary for my own workflow. Firstly, the volume of my contributions remains modest, allowing me to roughly recall the content of each commit. More fundamentally, I have yet to encounter a scenario that would require me to revert to a previous state.\
\
Before building this website, I had almost no knowledge of `CSS`. My `style.css` file is probably full of messy, non-standard code. Since a large part of it was generated by AI, I don’t even have the ability to maintain it properly. Fortunately, at least for now, it seems to work just as I imagined. I hope to fill this knowledge gap in the days to come.