project:
  type: website
  resources: 
    - assets/
website:
  title: "Yijia Zhao"
  favicon: assets/favicon.svg
  site-url: "https://blog.yijialog.org/"
  navbar: 
    left:
      - icon: file-post
        href: posts.qmd
        text: Posts
      - icon: file-person
        href: about.qmd
        text: About
  search:
    location: navbar
    type: overlay
    copy-button: true
  page-footer:
    center: "[Copyright](/credits.qmd) © 2026 Yijia Zhao | Built with [Quarto](https://quarto.org/)"
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    theme-toggle:
      location: navbar
      default-appearance: auto
    css: styles.css
    code-copy: true
    toc: true
    toc-location: right
    mathjax: true